#!/bin/bash

function ensure::jq() {
    REQUIRED_PKG=jq
    PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")
    echo "Checking for $REQUIRED_PKG: {STATUS} $PKG_OK"
    if [ "" = "$PKG_OK" ]; then
      echo "⛔ No $REQUIRED_PKG. Setting up $REQUIRED_PKG."
      sudo apt-get --yes install $REQUIRED_PKG
    fi
}

function ensure::curl() {
    REQUIRED_PKG=curl
    PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")
    echo "Checking for $REQUIRED_PKG: {STATUS} $PKG_OK"
    if [ "" = "$PKG_OK" ]; then
      echo "⛔ No $REQUIRED_PKG. Setting up $REQUIRED_PKG."
      sudo apt-get --yes install $REQUIRED_PKG
    fi
}

ensure::jq
ensure::curl

REPO=google/google-java-format
JAR_URL=$(curl -s https://api.github.com/repos/${REPO}/releases/latest | jq -r '.assets[0].browser_download_url')
JAR_NAME=$(echo ${JAR_URL##*/})
CACHE_DIR="$HOME/.cache/google-java-format-git-pre-commit-hook"
JAR_FILE="$CACHE_DIR/$JAR_NAME"


echo "====================================="
echo " ☕️ Running pre-commit code formatter"
echo "====================================="
if [[ ! -f "$JAR_FILE" ]]
then
    echo "Setting up google-java-format"
    mkdir -p "$CACHE_DIR"
    curl -L "$JAR_URL" -o "$JAR_FILE"

fi
changed_java_files=$(git diff --cached --name-only --diff-filter=ACMR | grep ".*java$" || true)
if [[ -n "$changed_java_files" ]]
then
    echo "🗃️: The following files will checked and reformatted:"
    echo "$changed_java_files"
    if ! java -jar "$JAR_FILE" --replace --set-exit-if-changed $changed_java_files
    then
        echo "\n♻✍️: Some files were reformatted"
    else
        echo "✅️ All good!"
    fi
    git add $changed_java_files
else
    echo "✅️ All good!"
fi
echo "=================================="